# Default values for pgdump-to-s3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gak0/pgdump-to-s3
  tag: latest
  pullPolicy: Always

cron:
  schedule: "*/1 * * * *"

s3:
  key: REQUIRED
  secret: REQUIRED
  bucket: REQUIRED
  region: REQUIRED

  # The generated name will be a timestamp surrounded by the prefix and suffix, e.g.:
  # my-backups/site-2032-01-01T12:34:45Z.pg_dump
  prefix: "my-backups/site-"
  suffix: ".pg_dump"

postgresql:
  host: REQUIRED
  user: REQUIRED
  password: REQUIRED
  database: REQUIRED

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
